// Code generated by ogen, DO NOT EDIT.

package agentAPI

// OperationName is the ogen operation name
type OperationName = string

const (
	APICoreStatusGetOperation        OperationName = "APICoreStatusGet"
	APIExportArchivePostOperation    OperationName = "APIExportArchivePost"
	APIFsCreatePostOperation         OperationName = "APIFsCreatePost"
	APIFsDeletePostOperation         OperationName = "APIFsDeletePost"
	APIFsGetGetOperation             OperationName = "APIFsGetGet"
	APIFsIdsGetOperation             OperationName = "APIFsIdsGet"
	APIParsingBookCheckPostOperation OperationName = "APIParsingBookCheckPost"
	APIParsingBookMultiPostOperation OperationName = "APIParsingBookMultiPost"
	APIParsingBookPostOperation      OperationName = "APIParsingBookPost"
	APIParsingPageCheckPostOperation OperationName = "APIParsingPageCheckPost"
	APIParsingPagePostOperation      OperationName = "APIParsingPagePost"
)
