// Code generated by ogen, DO NOT EDIT.

package agentAPI

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIExportArchivePostParams is parameters of POST /api/export/archive operation.
type APIExportArchivePostParams struct {
	// ID книги в системе.
	BookID uuid.UUID
	// URL книги в системе.
	BookURL OptURI
	// Название книги.
	BookName string
}

func unpackAPIExportArchivePostParams(packed middleware.Parameters) (params APIExportArchivePostParams) {
	{
		key := middleware.ParameterKey{
			Name: "book-id",
			In:   "header",
		}
		params.BookID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "book-url",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.BookURL = v.(OptURI)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "book-name",
			In:   "header",
		}
		params.BookName = packed[key].(string)
	}
	return params
}

func decodeAPIExportArchivePostParams(args [0]string, argsEscaped bool, r *http.Request) (params APIExportArchivePostParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: book-id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "book-id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.BookID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "book-id",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: book-url.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "book-url",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBookURLVal url.URL
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToURL(val)
					if err != nil {
						return err
					}

					paramsDotBookURLVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.BookURL.SetTo(paramsDotBookURLVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "book-url",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: book-name.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "book-name",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BookName = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "book-name",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIFsCreatePostParams is parameters of POST /api/fs/create operation.
type APIFsCreatePostParams struct {
	// ID файла в системе.
	FileID uuid.UUID
}

func unpackAPIFsCreatePostParams(packed middleware.Parameters) (params APIFsCreatePostParams) {
	{
		key := middleware.ParameterKey{
			Name: "file-id",
			In:   "header",
		}
		params.FileID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIFsCreatePostParams(args [0]string, argsEscaped bool, r *http.Request) (params APIFsCreatePostParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: file-id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "file-id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "file-id",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIFsGetGetParams is parameters of GET /api/fs/get operation.
type APIFsGetGetParams struct {
	// ID файла в системе.
	FileID uuid.UUID
}

func unpackAPIFsGetGetParams(packed middleware.Parameters) (params APIFsGetGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "file-id",
			In:   "query",
		}
		params.FileID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIFsGetGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIFsGetGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: file-id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "file-id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "file-id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIHighwayFileIDExtGetParams is parameters of GET /api/highway/file/{id}.{ext} operation.
type APIHighwayFileIDExtGetParams struct {
	// ID файла в системе.
	ID uuid.UUID
	// MIME тип файла.
	Ext string
	// Токен для доступа к файлу.
	Token string
}

func unpackAPIHighwayFileIDExtGetParams(packed middleware.Parameters) (params APIHighwayFileIDExtGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "ext",
			In:   "path",
		}
		params.Ext = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "token",
			In:   "query",
		}
		params.Token = packed[key].(string)
	}
	return params
}

func decodeAPIHighwayFileIDExtGetParams(args [2]string, argsEscaped bool, r *http.Request) (params APIHighwayFileIDExtGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: ext.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ext",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ext = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ext",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: token.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "token",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Token = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "token",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
