// Code generated by ogen, DO NOT EDIT.
package serverAPI

type APIAgentDeletePostRes interface {
	aPIAgentDeletePostRes()
}

type APIAgentGetPostRes interface {
	aPIAgentGetPostRes()
}

type APIAgentListPostRes interface {
	aPIAgentListPostRes()
}

type APIAgentNewPostRes interface {
	aPIAgentNewPostRes()
}

type APIAgentTaskExportPostRes interface {
	aPIAgentTaskExportPostRes()
}

type APIAgentUpdatePostRes interface {
	aPIAgentUpdatePostRes()
}

type APIAttributeColorCreatePostRes interface {
	aPIAttributeColorCreatePostRes()
}

type APIAttributeColorDeletePostRes interface {
	aPIAttributeColorDeletePostRes()
}

type APIAttributeColorGetPostRes interface {
	aPIAttributeColorGetPostRes()
}

type APIAttributeColorListGetRes interface {
	aPIAttributeColorListGetRes()
}

type APIAttributeColorUpdatePostRes interface {
	aPIAttributeColorUpdatePostRes()
}

type APIAttributeCountGetRes interface {
	aPIAttributeCountGetRes()
}

type APIBookArchiveIDGetRes interface {
	aPIBookArchiveIDGetRes()
}

type APIBookDeletePostRes interface {
	aPIBookDeletePostRes()
}

type APIBookDetailsPostRes interface {
	aPIBookDetailsPostRes()
}

type APIBookListPostRes interface {
	aPIBookListPostRes()
}

type APIBookRawPostRes interface {
	aPIBookRawPostRes()
}

type APIBookRebuildPostRes interface {
	aPIBookRebuildPostRes()
}

type APIBookRestorePostRes interface {
	aPIBookRestorePostRes()
}

type APIBookUpdatePostRes interface {
	aPIBookUpdatePostRes()
}

type APIBookVerifyPostRes interface {
	aPIBookVerifyPostRes()
}

type APIDeduplicateBookByPageBodyPostRes interface {
	aPIDeduplicateBookByPageBodyPostRes()
}

type APIDeduplicateBooksByPagePostRes interface {
	aPIDeduplicateBooksByPagePostRes()
}

type APIDeduplicateComparePostRes interface {
	aPIDeduplicateComparePostRes()
}

type APIDeduplicateDeadHashByBookPagesCreatePostRes interface {
	aPIDeduplicateDeadHashByBookPagesCreatePostRes()
}

type APIDeduplicateDeadHashByBookPagesDeletePostRes interface {
	aPIDeduplicateDeadHashByBookPagesDeletePostRes()
}

type APIDeduplicateDeadHashByPageCreatePostRes interface {
	aPIDeduplicateDeadHashByPageCreatePostRes()
}

type APIDeduplicateDeadHashByPageDeletePostRes interface {
	aPIDeduplicateDeadHashByPageDeletePostRes()
}

type APIDeduplicateDeleteAllPagesByBookPostRes interface {
	aPIDeduplicateDeleteAllPagesByBookPostRes()
}

type APIDeduplicateDeleteAllPagesByHashPostRes interface {
	aPIDeduplicateDeleteAllPagesByHashPostRes()
}

type APIDeduplicateDeleteBookDeadHashedPagesPostRes interface {
	aPIDeduplicateDeleteBookDeadHashedPagesPostRes()
}

type APIDeduplicateUniquePagesPostRes interface {
	aPIDeduplicateUniquePagesPostRes()
}

type APIFileIDGetRes interface {
	aPIFileIDGetRes()
}

type APIFsCreatePostRes interface {
	aPIFsCreatePostRes()
}

type APIFsDeletePostRes interface {
	aPIFsDeletePostRes()
}

type APIFsGetPostRes interface {
	aPIFsGetPostRes()
}

type APIFsListPostRes interface {
	aPIFsListPostRes()
}

type APIFsRemoveMismatchPostRes interface {
	aPIFsRemoveMismatchPostRes()
}

type APIFsTransferBookPostRes interface {
	aPIFsTransferBookPostRes()
}

type APIFsTransferPostRes interface {
	aPIFsTransferPostRes()
}

type APIFsUpdatePostRes interface {
	aPIFsUpdatePostRes()
}

type APIFsValidatePostRes interface {
	aPIFsValidatePostRes()
}

type APILabelDeletePostRes interface {
	aPILabelDeletePostRes()
}

type APILabelGetPostRes interface {
	aPILabelGetPostRes()
}

type APILabelPresetCreatePostRes interface {
	aPILabelPresetCreatePostRes()
}

type APILabelPresetDeletePostRes interface {
	aPILabelPresetDeletePostRes()
}

type APILabelPresetGetPostRes interface {
	aPILabelPresetGetPostRes()
}

type APILabelPresetListGetRes interface {
	aPILabelPresetListGetRes()
}

type APILabelPresetUpdatePostRes interface {
	aPILabelPresetUpdatePostRes()
}

type APILabelSetPostRes interface {
	aPILabelSetPostRes()
}

type APIPageBodyPostRes interface {
	aPIPageBodyPostRes()
}

type APIParsingBookExistsPostRes interface {
	aPIParsingBookExistsPostRes()
}

type APIParsingPageExistsPostRes interface {
	aPIParsingPageExistsPostRes()
}

type APISystemDeduplicateArchivePostRes interface {
	aPISystemDeduplicateArchivePostRes()
}

type APISystemHandlePostRes interface {
	aPISystemHandlePostRes()
}

type APISystemImportArchivePostRes interface {
	aPISystemImportArchivePostRes()
}

type APISystemInfoGetRes interface {
	aPISystemInfoGetRes()
}

type APISystemTaskCreatePostRes interface {
	aPISystemTaskCreatePostRes()
}

type APISystemTaskResultsGetRes interface {
	aPISystemTaskResultsGetRes()
}

type APISystemWorkerConfigPostRes interface {
	aPISystemWorkerConfigPostRes()
}

type APIUserLoginPostRes interface {
	aPIUserLoginPostRes()
}
